version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: npm
    directories:
      - /
      - /api
      - /app
      - /lib/*
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
