# https://gashmob.github.io/minecraft-monitor/configuration/application/config.toml/

[[logger]]
type = "file"
dir = "/var/log/minecraft-monitor/"
level = "trace"

[[logger]]
type = "console"
level = "trace"
