name: Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [ published ]

env:
  HUSKY: 0

permissions:
  contents: write
  packages: write

jobs:
  metadata:
    name: Get metadata
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Version
        id: version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
          else
            echo "version=devel" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Run build
        run: |
          nix develop --command pnpm i
          nix develop --command pnpm build

      - name: Archive dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: application-build
          path: |
            api/dist
            app/dist
          retention-days: 1

  test-build:
    name: Test build docker image
    runs-on: ubuntu-22.04
    needs:
      - build
      - metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: application-build
          path: ${{ github.workspace }}

      - name: Check presence of dist
        run: |
          ls api/dist
          ls app/dist

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

      - name: Test build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          target: production
          push: false
          tags: "ghcr.io/gashmob/minecraft-monitor:latest,ghcr.io/gashmob/minecraft-monitor:${{ needs.metadata.outputs.version }}"

  publish:
    if: github.ref == 'refs/heads/master'
    name: Publish results
    runs-on: ubuntu-22.04
    needs:
      - build
      - metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: application-build
          path: ${{ github.workspace }}

      - name: Check presence of dist
        run: |
          ls api/dist
          ls app/dist

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

      - name: Test build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          target: production
          push: false
          tags: "ghcr.io/gashmob/minecraft-monitor:latest,ghcr.io/gashmob/minecraft-monitor:${{ needs.metadata.outputs.version }}"

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          target: production
          push: true
          tags: "ghcr.io/gashmob/minecraft-monitor:latest,ghcr.io/gashmob/minecraft-monitor:${{ needs.metadata.outputs.version }}"
