name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  HUSKY: 0

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Run build
        run: |
          nix develop --command pnpm i
          nix develop --command pnpm test

  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Run build
        run: |
          nix develop --command pnpm i
          nix develop --command pnpm build
          nix develop --command pnpm --filter=app run e2e-test

  build-test:
    name: Build test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Run build
        run: |
          nix develop --command pnpm i
          nix develop --command pnpm build

  typecheck:
    name: Typecheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Run type-check
        run: |
          nix develop --command pnpm i
          nix develop --command pnpm run type-check

  format:
    name: Format + Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0

      - name: Install dependencies
        run: nix develop --command pnpm i

      - name: Run format
        run: |
          nix develop --command pnpm run format
          if [[ -z "$(git status --porcelain)" ]]; then
            exit 0
          else
            exit 1
          fi
      - name: Run lint
        run: |
          nix develop --command pnpm run lint
          if [[ -z "$(git status --porcelain)" ]]; then
            exit 0
          else
            exit 1
          fi
